rules:
    indentation:
        - 1
        -
            size: 4
    single-line-per-selector:
        - 0
    leading-zero:
        - 1
        -
            include: true
    no-ids:
        - 0
    no-qualifying-elements:
        - 0
    no-url-domains:
        - 0
    no-url-protocols:
        - 0
