language: node_js
node_js:
    - lts/*
    - node
dist: xenial
cache:
    directories:
        - ~/.npm
        - ~/.cache

before_install:
    - chmod +x ./setup.sh
    - ./setup.sh

install:
    - npm ci
