language: node_js
node_js:
    - "10.4.0"
dist: trusty
sudo: false
cache:
    directories:
        - ~/.npm
        - ~/.cache

before_install:
    - chmod +x ./setup.sh
    - ./setup.sh

install:
    - npm ci
